// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/models/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2663016188176459942),
    name: 'CustomerEntity',
    lastPropertyId: const obx_int.IdUid(7, 3644725006481386194),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1307233880966763254),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 328166366318766191),
        name: 'remoteId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6130055082996551324),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 201049710319201889),
        name: 'tenantId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8264429249342573298),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4332120428958898688),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4928503661416413075),
        name: 'pricingTier',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3644725006481386194),
        name: 'currentDebt',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5531137623161034724),
    name: 'InvoiceEntity',
    lastPropertyId: const obx_int.IdUid(8, 8187994674395658089),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8531954259554273812),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1944761609547070821),
        name: 'ulid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 2309866534840227857),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1779048161110390798),
        name: 'tenantId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8966052436897499191),
        name: 'customerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1479551716555940207),
        name: 'totalAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6837670407634145275),
        name: 'paymentMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4900072845697448333),
        name: 'createdAtLocal',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8187994674395658089),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'lineItems',
        srcEntity: 'LineItemEntity',
        srcField: 'invoice',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6182633476752569592),
    name: 'ItemEntity',
    lastPropertyId: const obx_int.IdUid(10, 4946975983553551052),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 124136014019064196),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6218674716298404177),
        name: 'remoteId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 2658613417335108708),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4226361321943184404),
        name: 'tenantId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2982055017369438240),
        name: 'barcode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2434470281846534600),
        name: 'nameTranslationsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7327928155076290722),
        name: 'pricesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3667995968499113522),
        name: 'qtyInStock',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4935041455890771306),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6561166034912542433),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4946975983553551052),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1691670028453853020),
    name: 'LineItemEntity',
    lastPropertyId: const obx_int.IdUid(6, 4298721453911347209),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4081969096602119770),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 579018565911227918),
        name: 'itemId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4833165145563910357),
        name: 'qty',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6744700554683913424),
        name: 'unitPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1279993070822374773),
        name: 'pricingTier',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4298721453911347209),
        name: 'invoiceId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 3494718874245362246),
        relationField: 'invoice',
        relationTarget: 'InvoiceEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1546742219701097604),
    name: 'PendingSyncEntity',
    lastPropertyId: const obx_int.IdUid(7, 7284872886200148576),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8096487438430823563),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4962537839812333434),
        name: 'entityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4924592195932122149),
        name: 'entityUlid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7848399513680375486),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3023898745587912242),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7001571526103358697),
        name: 'lastAttemptAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7284872886200148576),
        name: 'lastError',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1546742219701097604),
    lastIndexId: const obx_int.IdUid(4, 3494718874245362246),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CustomerEntity: obx_int.EntityDefinition<CustomerEntity>(
      model: _entities[0],
      toOneRelations: (CustomerEntity object) => [],
      toManyRelations: (CustomerEntity object) => {},
      getId: (CustomerEntity object) => object.id,
      setId: (CustomerEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CustomerEntity object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        final tenantIdOffset = fbb.writeString(object.tenantId);
        final nameOffset = fbb.writeString(object.name);
        final phoneOffset = fbb.writeString(object.phone);
        final pricingTierOffset = fbb.writeString(object.pricingTier);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.addOffset(2, tenantIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, pricingTierOffset);
        fbb.addFloat64(6, object.currentDebt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final tenantIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final pricingTierParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final currentDebtParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = CustomerEntity(
          id: idParam,
          remoteId: remoteIdParam,
          tenantId: tenantIdParam,
          name: nameParam,
          phone: phoneParam,
          pricingTier: pricingTierParam,
          currentDebt: currentDebtParam,
        );

        return object;
      },
    ),
    InvoiceEntity: obx_int.EntityDefinition<InvoiceEntity>(
      model: _entities[1],
      toOneRelations: (InvoiceEntity object) => [],
      toManyRelations: (InvoiceEntity object) => {
        obx_int.RelInfo<LineItemEntity>.toOneBacklink(
          6,
          object.id,
          (LineItemEntity srcObject) => srcObject.invoice,
        ): object.lineItems,
      },
      getId: (InvoiceEntity object) => object.id,
      setId: (InvoiceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (InvoiceEntity object, fb.Builder fbb) {
        final ulidOffset = fbb.writeString(object.ulid);
        final tenantIdOffset = fbb.writeString(object.tenantId);
        final customerIdOffset = object.customerId == null
            ? null
            : fbb.writeString(object.customerId!);
        final paymentModeOffset = fbb.writeString(object.paymentMode);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ulidOffset);
        fbb.addOffset(2, tenantIdOffset);
        fbb.addOffset(3, customerIdOffset);
        fbb.addFloat64(4, object.totalAmount);
        fbb.addOffset(5, paymentModeOffset);
        fbb.addInt64(6, object.createdAtLocal.millisecondsSinceEpoch);
        fbb.addBool(7, object.isSynced);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ulidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final tenantIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final customerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final totalAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final paymentModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtLocalParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = InvoiceEntity(
          id: idParam,
          ulid: ulidParam,
          tenantId: tenantIdParam,
          customerId: customerIdParam,
          totalAmount: totalAmountParam,
          paymentMode: paymentModeParam,
          createdAtLocal: createdAtLocalParam,
          isSynced: isSyncedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<InvoiceEntity>(
          object.lineItems,
          store,
          obx_int.RelInfo<LineItemEntity>.toOneBacklink(
            6,
            object.id,
            (LineItemEntity srcObject) => srcObject.invoice,
          ),
        );
        return object;
      },
    ),
    ItemEntity: obx_int.EntityDefinition<ItemEntity>(
      model: _entities[2],
      toOneRelations: (ItemEntity object) => [],
      toManyRelations: (ItemEntity object) => {},
      getId: (ItemEntity object) => object.id,
      setId: (ItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ItemEntity object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        final tenantIdOffset = fbb.writeString(object.tenantId);
        final barcodeOffset = object.barcode == null
            ? null
            : fbb.writeString(object.barcode!);
        final nameTranslationsJsonOffset = fbb.writeString(
          object.nameTranslationsJson,
        );
        final pricesJsonOffset = fbb.writeString(object.pricesJson);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.addOffset(2, tenantIdOffset);
        fbb.addOffset(3, barcodeOffset);
        fbb.addOffset(4, nameTranslationsJsonOffset);
        fbb.addOffset(5, pricesJsonOffset);
        fbb.addFloat64(6, object.qtyInStock);
        fbb.addBool(7, object.isActive);
        fbb.addBool(8, object.isSynced);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final tenantIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final barcodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final nameTranslationsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final pricesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final qtyInStockParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object = ItemEntity(
          id: idParam,
          remoteId: remoteIdParam,
          tenantId: tenantIdParam,
          barcode: barcodeParam,
          nameTranslationsJson: nameTranslationsJsonParam,
          pricesJson: pricesJsonParam,
          qtyInStock: qtyInStockParam,
          isActive: isActiveParam,
          isSynced: isSyncedParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    LineItemEntity: obx_int.EntityDefinition<LineItemEntity>(
      model: _entities[3],
      toOneRelations: (LineItemEntity object) => [object.invoice],
      toManyRelations: (LineItemEntity object) => {},
      getId: (LineItemEntity object) => object.id,
      setId: (LineItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (LineItemEntity object, fb.Builder fbb) {
        final itemIdOffset = fbb.writeString(object.itemId);
        final pricingTierOffset = fbb.writeString(object.pricingTier);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, itemIdOffset);
        fbb.addFloat64(2, object.qty);
        fbb.addFloat64(3, object.unitPrice);
        fbb.addOffset(4, pricingTierOffset);
        fbb.addInt64(5, object.invoice.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final itemIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final qtyParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final unitPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final pricingTierParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = LineItemEntity(
          id: idParam,
          itemId: itemIdParam,
          qty: qtyParam,
          unitPrice: unitPriceParam,
          pricingTier: pricingTierParam,
        );
        object.invoice.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.invoice.attach(store);
        return object;
      },
    ),
    PendingSyncEntity: obx_int.EntityDefinition<PendingSyncEntity>(
      model: _entities[4],
      toOneRelations: (PendingSyncEntity object) => [],
      toManyRelations: (PendingSyncEntity object) => {},
      getId: (PendingSyncEntity object) => object.id,
      setId: (PendingSyncEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PendingSyncEntity object, fb.Builder fbb) {
        final entityTypeOffset = fbb.writeString(object.entityType);
        final entityUlidOffset = fbb.writeString(object.entityUlid);
        final lastErrorOffset = object.lastError == null
            ? null
            : fbb.writeString(object.lastError!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entityTypeOffset);
        fbb.addOffset(2, entityUlidOffset);
        fbb.addInt64(3, object.retryCount);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.lastAttemptAt?.millisecondsSinceEpoch);
        fbb.addOffset(6, lastErrorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastAttemptAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityUlidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object =
            PendingSyncEntity(
                id: idParam,
                entityType: entityTypeParam,
                entityUlid: entityUlidParam,
                retryCount: retryCountParam,
                createdAt: createdAtParam,
              )
              ..lastAttemptAt = lastAttemptAtValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(lastAttemptAtValue)
              ..lastError = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 16);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CustomerEntity] entity fields to define ObjectBox queries.
class CustomerEntity_ {
  /// See [CustomerEntity.id].
  static final id = obx.QueryIntegerProperty<CustomerEntity>(
    _entities[0].properties[0],
  );

  /// See [CustomerEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<CustomerEntity>(
    _entities[0].properties[1],
  );

  /// See [CustomerEntity.tenantId].
  static final tenantId = obx.QueryStringProperty<CustomerEntity>(
    _entities[0].properties[2],
  );

  /// See [CustomerEntity.name].
  static final name = obx.QueryStringProperty<CustomerEntity>(
    _entities[0].properties[3],
  );

  /// See [CustomerEntity.phone].
  static final phone = obx.QueryStringProperty<CustomerEntity>(
    _entities[0].properties[4],
  );

  /// See [CustomerEntity.pricingTier].
  static final pricingTier = obx.QueryStringProperty<CustomerEntity>(
    _entities[0].properties[5],
  );

  /// See [CustomerEntity.currentDebt].
  static final currentDebt = obx.QueryDoubleProperty<CustomerEntity>(
    _entities[0].properties[6],
  );
}

/// [InvoiceEntity] entity fields to define ObjectBox queries.
class InvoiceEntity_ {
  /// See [InvoiceEntity.id].
  static final id = obx.QueryIntegerProperty<InvoiceEntity>(
    _entities[1].properties[0],
  );

  /// See [InvoiceEntity.ulid].
  static final ulid = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[1],
  );

  /// See [InvoiceEntity.tenantId].
  static final tenantId = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[2],
  );

  /// See [InvoiceEntity.customerId].
  static final customerId = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[3],
  );

  /// See [InvoiceEntity.totalAmount].
  static final totalAmount = obx.QueryDoubleProperty<InvoiceEntity>(
    _entities[1].properties[4],
  );

  /// See [InvoiceEntity.paymentMode].
  static final paymentMode = obx.QueryStringProperty<InvoiceEntity>(
    _entities[1].properties[5],
  );

  /// See [InvoiceEntity.createdAtLocal].
  static final createdAtLocal = obx.QueryDateProperty<InvoiceEntity>(
    _entities[1].properties[6],
  );

  /// See [InvoiceEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<InvoiceEntity>(
    _entities[1].properties[7],
  );

  /// see [InvoiceEntity.lineItems]
  static final lineItems =
      obx.QueryBacklinkToMany<LineItemEntity, InvoiceEntity>(
        LineItemEntity_.invoice,
      );
}

/// [ItemEntity] entity fields to define ObjectBox queries.
class ItemEntity_ {
  /// See [ItemEntity.id].
  static final id = obx.QueryIntegerProperty<ItemEntity>(
    _entities[2].properties[0],
  );

  /// See [ItemEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<ItemEntity>(
    _entities[2].properties[1],
  );

  /// See [ItemEntity.tenantId].
  static final tenantId = obx.QueryStringProperty<ItemEntity>(
    _entities[2].properties[2],
  );

  /// See [ItemEntity.barcode].
  static final barcode = obx.QueryStringProperty<ItemEntity>(
    _entities[2].properties[3],
  );

  /// See [ItemEntity.nameTranslationsJson].
  static final nameTranslationsJson = obx.QueryStringProperty<ItemEntity>(
    _entities[2].properties[4],
  );

  /// See [ItemEntity.pricesJson].
  static final pricesJson = obx.QueryStringProperty<ItemEntity>(
    _entities[2].properties[5],
  );

  /// See [ItemEntity.qtyInStock].
  static final qtyInStock = obx.QueryDoubleProperty<ItemEntity>(
    _entities[2].properties[6],
  );

  /// See [ItemEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<ItemEntity>(
    _entities[2].properties[7],
  );

  /// See [ItemEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<ItemEntity>(
    _entities[2].properties[8],
  );

  /// See [ItemEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ItemEntity>(
    _entities[2].properties[9],
  );
}

/// [LineItemEntity] entity fields to define ObjectBox queries.
class LineItemEntity_ {
  /// See [LineItemEntity.id].
  static final id = obx.QueryIntegerProperty<LineItemEntity>(
    _entities[3].properties[0],
  );

  /// See [LineItemEntity.itemId].
  static final itemId = obx.QueryStringProperty<LineItemEntity>(
    _entities[3].properties[1],
  );

  /// See [LineItemEntity.qty].
  static final qty = obx.QueryDoubleProperty<LineItemEntity>(
    _entities[3].properties[2],
  );

  /// See [LineItemEntity.unitPrice].
  static final unitPrice = obx.QueryDoubleProperty<LineItemEntity>(
    _entities[3].properties[3],
  );

  /// See [LineItemEntity.pricingTier].
  static final pricingTier = obx.QueryStringProperty<LineItemEntity>(
    _entities[3].properties[4],
  );

  /// See [LineItemEntity.invoice].
  static final invoice = obx.QueryRelationToOne<LineItemEntity, InvoiceEntity>(
    _entities[3].properties[5],
  );
}

/// [PendingSyncEntity] entity fields to define ObjectBox queries.
class PendingSyncEntity_ {
  /// See [PendingSyncEntity.id].
  static final id = obx.QueryIntegerProperty<PendingSyncEntity>(
    _entities[4].properties[0],
  );

  /// See [PendingSyncEntity.entityType].
  static final entityType = obx.QueryStringProperty<PendingSyncEntity>(
    _entities[4].properties[1],
  );

  /// See [PendingSyncEntity.entityUlid].
  static final entityUlid = obx.QueryStringProperty<PendingSyncEntity>(
    _entities[4].properties[2],
  );

  /// See [PendingSyncEntity.retryCount].
  static final retryCount = obx.QueryIntegerProperty<PendingSyncEntity>(
    _entities[4].properties[3],
  );

  /// See [PendingSyncEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<PendingSyncEntity>(
    _entities[4].properties[4],
  );

  /// See [PendingSyncEntity.lastAttemptAt].
  static final lastAttemptAt = obx.QueryDateProperty<PendingSyncEntity>(
    _entities[4].properties[5],
  );

  /// See [PendingSyncEntity.lastError].
  static final lastError = obx.QueryStringProperty<PendingSyncEntity>(
    _entities[4].properties[6],
  );
}
